export const users_form_fields = {
    firstName: {
        key: 'users-form-field-firstName-key',
        name: 'firstName',
        mappingId: 'firstName',
        label: 'First Name',
        required: true,
        placeholder: 'Enter first name',
        width: {xs: 12, md: 6},
        type: 'text',
    },
    lastName: {
        key: 'users-form-field-lastName-key',
        name: 'lastName',
        mappingId: 'lastName',
        label: 'Last Name',
        required: true,
        placeholder: 'Enter last name',
        width: {xs: 12, md: 6},
        type: 'text',
    },
    email: {
        key: 'users-form-field-email-key',
        name: 'email',
        mappingId: 'email',
        label: 'Email',
        required: true,
        placeholder: 'Enter email',
        width: {xs: 12, md: 12},
        type: 'text',
    },
    password: {
        key: 'users-form-field-password-key',
        name: 'password',
        mappingId: 'password',
        label: 'Password',
        required: true,
        placeholder: 'Enter password',
        width: {xs: 12, md: 12},
        type: 'password',
    },
    confirm_password: {
        key: 'users-form-field-confirm_password-key',
        name: 'confirm_password',
        mappingId: 'confirm_password',
        label: 'Confirm Password',
        required: true,
        placeholder: 'Confirm password',
        width: {xs: 12, md: 12},
        type: 'password',
    },
}